/* This file is auto-generated by (yogi loader --yes) */

/*jshint maxlen:900, eqeqeq: false */

/**
 * YUI 3 module metadata
 * @module loader
 * @submodule loader-yui3
 */
YUI.Env[Y.version].modules = YUI.Env[Y.version].modules || {
    "rednose-app-base": {
        "requires": [
            "app-base",
            "cssgrids",
            "event-custom",
            "handlebars-base",
            "rednose-app-templates",
            "rednose-panel"
        ],
        "skinnable": true
    },
    "rednose-contextmenu": {
        "requires": [
            "base",
            "panel",
            "plugin",
            "widget",
            "overlay"
        ]
    },
    "rednose-controlform": {
        "requires": [
            "calendar",
            "dd-proxy",
            "dd-constrain",
            "node",
            "model-list",
            "model",
            "base",
            "rednose-dialog",
            "rednose-contextmenu"
        ]
    },
    "rednose-css": {
        "type": "css"
    },
    "rednose-datatable": {
        "requires": [
            "datatable-base",
            "datatable-scroll",
            "datatable-sort"
        ],
        "skinnable": true
    },
    "rednose-datatable-select": {
        "requires": [
            "rednose-datatable",
            "plugin"
        ]
    },
    "rednose-dd": {
        "requires": [
            "rednose-anim",
            "rednose-dd-css",
            "view"
        ]
    },
    "rednose-dd-css": {
        "type": "css"
    },
    "rednose-dialog": {
        "requires": [
            "dd",
            "dd-plugin",
            "json-parse",
            "rednose-css",
            "rednose-panel",
            "node",
            "node-event-simulate",
            "widget"
        ],
        "skinnable": true
    },
    "rednose-dropdown": {
        "requires": [
            "base",
            "rednose-css",
            "node",
            "gallery-bootstrap-dropdown"
        ]
    },
    "rednose-grid": {
        "requires": [
            "handlebars",
            "rednose-grid-select",
            "rednose-contextmenu",
            "model-list",
            "view"
        ],
        "skinnable": true
    },
    "rednose-grid-select": {},
    "rednose-model-spinner": {
        "requires": [
            "rednose-app-base",
            "model"
        ]
    },
    "rednose-model-tree": {
        "requires": [
            "model",
            "io"
        ]
    },
    "rednose-model-undo": {
        "requires": [
            "model"
        ]
    },
    "rednose-navbar": {
        "requires": [
            "handlebars",
            "gallery-bootstrap-dropdown"
        ],
        "skinnable": true
    },
    "rednose-navbar-recent": {
        "requires": [
            "cookie",
            "plugin",
            "rednose-navbar"
        ]
    },
    "rednose-nodescroll": {
        "requires": [
            "node",
            "event",
            "dd",
            "anim"
        ]
    },
    "rednose-panel": {
        "requires": [
            "panel"
        ]
    },
    "rednose-tooltip": {
        "requires": [
            "gallery-bootstrap-tooltip"
        ]
    },
    "rednose-treeview": {
        "requires": [
            "gallery-sm-treeview",
            "rednose-model-tree",
            "rednose-treeview-anim",
            "rednose-treeview-dd",
            "rednose-treeview-templates",
            "rednose-treeview-select",
            "node"
        ],
        "skinnable": true,
        "supersedes": [
            "gallery-sm-treeview-templates"
        ]
    },
    "rednose-treeview-anim": {
        "requires": [
            "rednose-anim",
            "rednose-treeview",
            "transition"
        ]
    },
    "rednose-treeview-dd": {
        "requires": [
            "rednose-dd",
            "rednose-treeview"
        ]
    },
    "rednose-treeview-select": {
        "requires": [
            "rednose-treeview"
        ]
    },
    "rednose-treeview-templates": {
        "requires": [
            "template-micro"
        ]
    },
    "rednose-view-nav": {
        "requires": [
            "event-custom",
            "rednose-widget-nav-container",
            "view"
        ]
    },
    "rednose-widget-nav-container": {
        "requires": [
            "widget",
            "widget-buttons",
            "widget-stdmod"
        ]
    }
};
YUI.Env[Y.version].md5 = '71e28e39571a040ab721673cac4c7333';
